server:
  port: 8082

symmetric:
  key: greenavengers3000abcd3000efvde

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_greeney?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_greeney
    password: 1234
  thymeleaf:
    cache: false


  # spring data jpa 설정
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# 파일(이미지) 업로드할 때 크기 제한 설정

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
cloud:
  aws:
    s3:
      bucket: greeney-bucket
    stack:
        auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAUJHXOY4CPPC7XRX7
      secretKey: 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
